### ISSUE TITLE
Define content registry architecture

### ISSUE THREAD

**Issue by jmbenedetto** [byhumane/content_management#11]
# Story
As a content developer I need a content registry to easily find and reuse existing contents.

# Acceptance criteria
- [ ] Easy to create a new content.
- [ ] Easy to update an existing content.
- [ ] All changes tracked.
- [ ] Content lifecycle managed.
- [ ] Easy to go from the registry to the content and vice-versa.
- [ ] Easy to define parts of the content.
- [ ] Easy to see where the content is used (other contents and courses).
- [ ] Easy to relate the content with the overall knowledge structure (process, variants, task)

# Tasks
- [ ] Study different solutions
- [ ] Define the technical solution to be used
- [ ] Define the parametrization needed on the solution
