### ISSUE TITLE
Define knowledge tree solution architecture

### ISSUE THREAD

**Issue by jmbenedetto** [byhumane/content_management#12]
# Story
As a supply chain expert I need to map processes, variants, activities and additional information related to different aspects of the logistic operation, before designing the training plan.

# Acceptance criteria
- [x] Tabulated list of process, variants, tasks and additional information
- [x] Support for different relationships between different components
- [x] Relationship visualization
- [x] Easy to maintain
- [x] Easy to see related content and courses
- [x] All changes tracked

# Tasks
- [x] Study different solutions
- [x] Define the solution
- [ ] Define the parametrization needed on the solution

**Comment by jmbenedetto** [comment]
Definitions embedded on the file Content Organization.md
