### ISSUE TITLE
Course management architecture

### ISSUE THREAD

**Issue by jmbenedetto** [byhumane/content_management#13]
# Story
As a content developer I need a course registry to easily manage courses.

# Acceptance criteria
- [x] Easy to create and update courses.
- [x] All changes tracked.
- [x] Courses lifecycle managed.
- [x] Easy to define ordered contents.
- [x] Easy to relate the course with the overall knowledge structure (process, variants, task)

# Tasks
- [x] Study different solutions
- [x] Define the technical solution to be used
- [x] Define the parametrization needed on the solution

**Comment by jmbenedetto** [comment]
It was treated on the overall knowledge management effort.
